"""Safe UAE finance job discovery and selection agent.

This script is designed for GitHub Actions. It does not log in to job portals,
does not auto-apply, and does not send LinkedIn messages. It reads job leads from
one or more safe inputs, scores them against Christopher Nemala's CV profile, and
syncs selected jobs to Notion.

Supported inputs:
1. job_agent/job_leads.json committed manually or generated by another safe tool.
2. JOB_AGENT_LEADS_JSON environment variable containing JSON array of jobs.

Each job object:
{
  "title": "Credit Controller",
  "company": "Example Company",
  "location": "Dubai",
  "source": "LinkedIn",
  "link": "https://...",
  "description": "Full JD text..."
}
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Iterable

from job_selection_rules import JobRecord, score_job
from notion_selection_sync import create_job_page, NotionSyncError


DEFAULT_LEADS_FILE = Path(__file__).resolve().parent / "job_leads.json"


def load_jobs() -> list[JobRecord]:
    raw_jobs: list[dict] = []

    env_payload = os.getenv("JOB_AGENT_LEADS_JSON", "").strip()
    if env_payload:
        raw_jobs.extend(json.loads(env_payload))

    if DEFAULT_LEADS_FILE.exists():
        raw_jobs.extend(json.loads(DEFAULT_LEADS_FILE.read_text(encoding="utf-8")))

    return dedupe([to_job_record(item) for item in raw_jobs])


def to_job_record(item: dict) -> JobRecord:
    return JobRecord(
        title=(item.get("title") or "").strip(),
        company=(item.get("company") or "Unknown Company").strip(),
        location=(item.get("location") or "UAE").strip(),
        source=(item.get("source") or "Company Website").strip(),
        link=(item.get("link") or "").strip(),
        description=(item.get("description") or "").strip(),
    )


def dedupe(jobs: Iterable[JobRecord]) -> list[JobRecord]:
    seen: set[str] = set()
    output: list[JobRecord] = []
    for job in jobs:
        key = f"{job.title.lower()}|{job.company.lower()}|{job.link.lower()}"
        if key in seen:
            continue
        seen.add(key)
        output.append(job)
    return output


def main() -> None:
    max_jobs = int(os.getenv("JOB_AGENT_MAX_JOBS", "40"))
    min_score = int(os.getenv("JOB_AGENT_MIN_SCORE_TO_SAVE", "65"))

    jobs = load_jobs()[:max_jobs]
    print(f"Loaded {len(jobs)} job leads.")

    selected = 0
    skipped = 0
    failures = 0

    for job in jobs:
        scored = score_job(job)
        score = int(scored.get("match_score") or 0)
        priority = scored.get("priority")
        print(f"{score:03d} | {priority:6s} | {job.company} | {job.title}")

        if score < min_score or priority == "Skip":
            skipped += 1
            continue

        try:
            url = create_job_page(job, scored)
            selected += 1
            print(f"  Synced to Notion: {url}")
        except NotionSyncError as exc:
            failures += 1
            print(f"  Notion sync failed: {exc}")

    print("\nDaily UAE Finance Job Selection Report")
    print(f"Jobs scanned: {len(jobs)}")
    print(f"Selected to Notion: {selected}")
    print(f"Skipped: {skipped}")
    print(f"Failures: {failures}")

    if failures:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
